[theme]
base="dark"
primaryColor="#00C8FF"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"

[server]
runOnSave = true
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"